### ISSUE TITLE
시험 페이지 전송받은 값 에러

### ISSUE THREAD

**Issue by u-nij** [mjmjmj9840/Cheating-Stamp#47]
- **startTime, endTime** : 뭐시 문제여..

- 서버에서 전송받은 값 콘솔 출력 
![image](https://user-images.githubusercontent.com/61776419/131998046-5a9ba706-f764-49d0-9083-b2f88f04207b.png)

- DB에 저장된 값
![image](https://user-images.githubusercontent.com/61776419/131998223-5d2f14ad-fcc1-444d-bdd8-a3854a4e8079.png)

### 브랜치명
feature/47_exam

**Comment by mjmjmj9840** [comment]
자바스크립트에서 month를 받아올때 index가 0부터 시작돼서 month + 1로 출력되는걸로 알아용~~ 그냥 자바스크립트 코드에서 month - 1 해주면 될 듯!!

**Comment by u-nij** [comment]
!!!!!!!!!감사합니다잉~~!
